services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/coop
    volumes:
      - ./backend/coop:/app
    # Uses service_healthy to wait for the database to be ready before starting
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/orbiflow
    volumes:
      - ./frontend/orbiflow:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data: