# Generated by Django 6.0.4 on 2026-04-30 19:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('applies_to_cap', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('treasurer', 'Tesorero'), ('associate', 'Asociado')], default='associate', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('cbu', models.CharField(max_length=22, unique=True)),
                ('entry_date', models.DateField()),
                ('base_hours', models.IntegerField(default=8)),
                ('work_email', models.EmailField(max_length=254, unique=True)),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('emergency_contact', models.JSONField(default=dict, help_text='Guardar nombre, teléfono y vínculo')),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='associate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asociados',
                'db_table': 'associates',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('hour_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cap_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuraciones Globales',
                'db_table': 'global_configurations',
            },
        ),
        migrations.CreateModel(
            name='LiquidationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('applied_hour_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_cap_pct', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('reviewed', 'En Revisión'), ('closed', 'Cerrado')], default='open', max_length=15)),
            ],
            options={
                'verbose_name': 'Periodo de Liquidación',
                'verbose_name_plural': 'Periodos de Liquidación',
                'db_table': 'liquidation_periods',
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RetirementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.IntegerField()),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orbiflow.associate')),
                ('liquidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbiflow.liquidationperiod')),
            ],
            options={
                'verbose_name': 'Detalle de Retiro',
                'verbose_name_plural': 'Detalles de Retiros',
                'db_table': 'retirement_details',
                'unique_together': {('liquidation', 'associate')},
            },
        ),
        migrations.CreateModel(
            name='LiquidationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('retirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orbiflow.retirementdetail')),
            ],
            options={
                'verbose_name': 'Ítem de Liquidación',
                'verbose_name_plural': 'Ítems de Liquidación',
                'db_table': 'liquidation_items',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('fixed_amount', 'Monto Fijo'), ('percentage', 'Porcentaje')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_default', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='orbiflow.module')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'db_table': 'variants',
            },
        ),
        migrations.CreateModel(
            name='AssociateVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField(default=django.utils.timezone.now)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbiflow.associate')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orbiflow.variant')),
            ],
            options={
                'verbose_name': 'Variante por Asociado',
                'verbose_name_plural': 'Variantes por Asociados',
                'db_table': 'associate_variants',
                'unique_together': {('associate', 'variant')},
            },
        ),
    ]
