# Generated by Django 6.0.4 on 2026-05-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbiflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associate',
            name='work_email',
        ),
    ]
