# Generated by Django 6.0.4 on 2026-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbiflow', '0002_remove_associate_work_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='calculation_type',
            field=models.CharField(choices=[('simple', 'Valor Fijo / Porcentaje Simple'), ('seniority', 'Multiplicar por Años de Antigüedad')], default='simple', max_length=20),
        ),
    ]
