# Generated by Django 6.0

from django.db import migrations, models

import orbiflow.models.rules


class Migration(migrations.Migration):

    dependencies = [
        ('orbiflow', '0003_module_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associatevariant',
            name='activation_date',
            field=models.DateField(default=orbiflow.models.rules.default_activation_date),
        ),
    ]
